_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.51.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 5
layers:
    value: 2
learning_rate:
    value: 0.0003
model_dim:
    value: 128
vocab_size:
    value: 50257
