_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.7
            "5": 0.19.9
            "6": 4.51.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
