_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
