_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.9
            "6": 4.51.0
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 32
d_ff:
    value: 512
d_model:
    value: 128
epochs:
    value: 50
lr:
    value: 0.0001
max_len:
    value: 64
n_heads:
    value: 4
num_layers:
    value: 2
