_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.9
            "6": 4.51.2
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
