wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.1
    cli_version: 0.19.9
    framework: huggingface
    huggingface_version: 4.51.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1745407937
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      - 42
      - 55
      4: 3.13.1
      5: 0.19.9
      6: 4.51.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
