_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
